name: CI VelibData Pipeline

on:
  push:
    branches: [main, develop, Linda-release]
  pull_request:
    branches: [main, develop, Linda-release]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      AZURE_TENANT_ID:     ${{ secrets.ARM_TENANT_ID }}
      AZURE_CLIENT_ID:     ${{ secrets.ARM_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ADLS_ACCOUNT_NAME:   velibdatastorage
      LOG_LEVEL:           INFO

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Lint
        run: uv run ruff check src/ tests/

      - name: Tests
        run: uv run pytest --tb=short -q
